---
title: "Billboard Top 100"
author: "Tristan Caro"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r, include=FALSE}
library(tidyverse)
library(ggdist)
library(showtext)
library(ggsignif)
library(ggpubr)
library(ggfortify)
library(ggbiplot)
library(ggsci)
library(reticulate)
library(plotly)
```

# Import Data
```{r}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

# Use the following on first run
# tuesdata <- tidytuesdayR::tt_load('2021-09-14')
# tuesdata <- tidytuesdayR::tt_load(2021, week = 38)
# billboard <- tuesdata$billboard
# audio <- tuesdata$audio_features
# write_csv(billboard, "data/billboard.csv")
# write_csv(audio, "data/audio.csv")

# Use this once you've downloaded the data

billboard <- read_csv("data/billboard.csv")
audio <- read_csv("data/audio.csv")
```

```{r}
# Turn genres into a proper vector
audio_w_genres <- audio %>% 
mutate(
   audio_genre = spotify_genre %>% 
     str_remove_all("(^ *\\['?)|('?\\] *$)") %>% 
     str_split("', ?'")) %>%
unnest(audio_genre) %>% filter(nchar(audio_genre) > 0)

```



```{r}
explicitness_scale = c("#de3c14", "#59e3bc")

p_explicit <- audio %>% 
  filter(!is.na(spotify_track_explicit)) %>% 
  mutate(spotify_track_explicit = case_when(
    spotify_track_explicit == TRUE ~ "Explicit",
    spotify_track_explicit == FALSE ~ "Not Explicit")) %>% 
  ggplot(aes(x = spotify_track_explicit, 
             y = spotify_track_popularity, 
             color = spotify_track_explicit,
             fill = spotify_track_explicit)) +
  stat_dots(position = "dodge",
            size = 0.5) +
  stat_pointinterval(color = "black") +
  stat_signif(
    comparisons = list(c("Explicit", "Not Explicit")),
    map_signif_level = TRUE,
    color = "black",
    textsize = 6,
    ) +
  stat_compare_means(label.x = 1.37,
                     label.y = 100,
                     size = 3) +
  labs(legend = "",
       y = "Spotify Popularity Score",
       title = "Is explicit music more popular?",
       caption = "Source: Data.World | #TidyTuesday | @tris_caro",
       subtitle = "") +
  scale_color_manual(values = explicitness_scale) +
  coord_cartesian(ylim = c(0, 110)) +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")
p_explicit

#ggsave("p_explicit.png", p_explicit, dpi = 300, height = 8, width = 8)
```

```{r}
audio_cleaned_full <- audio %>% 
  drop_na() %>% 
  #filter(spotify_track_popularity > 90) %>% 
  mutate(spotify_track_popularity_bool = spotify_track_popularity > 80) %>% 
  select(-c(time_signature, tempo, valence, mode))  # don't want to compare these

audio_cleaned_numeric <- audio_cleaned_full %>% 
  select_if(is.numeric) # pass only rows w/ numeric values to PCA analysis

pca_audio <- prcomp(audio_cleaned_numeric)
```

```
pca_audio %>% autoplot(data = audio_cleaned_full,
                       loadings = TRUE,
                       loadings.label = TRUE,
                       loadings.label.size = 2,
                       colour = 'spotify_track_popularity_bool')
```

```{r}
pca_audio %>% ggbiplot(groups = factor(audio_cleaned_full$spotify_track_explicit),
                       ellipse = TRUE, circle = TRUE) +
  scale_color_npg() +
  theme_classic() +
  theme(legend.direction = 'horizontal', 
        legend.position = 'top',
        axis.line = element_blank(),
        )
```


```{r}

audio_lm <- lm(data = audio_w_genres, loudness~danceability)

audio_w_genres %>% 
  ggplot(aes(x = loudness,
             y = danceability, 
             color = audio_genre)) +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.2,
              alpha = 0.5) +
  geom_point(size = 0.1) +
  coord_polar() +
  labs(title = "Louder music more dance-y?",
       caption = "Source: Data.World | #TidyTuesday | @tris_caro") +
  scale_color_viridis_d(option = "plasma") +
  theme_classic() +
  theme(legend.position = "none",
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank())
```


```{r}
genre_count <- audio_w_genres %>%
  summarize(n = count(audio_genre))
```

```{r}
library(tidyverse)
library(lubridate)
#library(camcorder)

#gg_record(dir = "temp", device = "png", width = 15, height = 12, units = "in", dpi = 320)

billboard <- read_csv("data/billboard.csv")
audio_features <- read_csv("data/audio.csv")

billb_feat <- billboard %>% 
  left_join(audio_features) %>% 
  distinct(week_id, song, song_id, week_position, spotify_genre) %>% 
  mutate(
    week_id = mdy(week_id),
    year = year(week_id),
    spotify_genre = str_remove_all(spotify_genre, "\\[|\\]|'|\""),
    spotify_genre = str_split(spotify_genre, ", ")
    ) %>% 
  filter(spotify_genre != "" & !is.na(spotify_genre)) %>% 
  unnest(spotify_genre) %>% 
  group_by(year, spotify_genre) %>% 
  dplyr::count(year, spotify_genre)

```

```{r}
f1 = "Fira Sans Compressed"
f2 = "Futura"

ggplot(billb_feat, aes(x = year, y = n, fill = spotify_genre)) +
  geom_bar(position = "fill", stat = "identity", width = 1) +
  geom_text(aes(label = spotify_genre, size = n), position = position_fill(vjust = 0.5), check_overlap = TRUE, family = f1, color = "grey10") +
  scale_fill_viridis_d(option = "turbo", begin = 0.05, end = 0.95) +
  scale_size_continuous(range = c(0.4, 5)) +
  scale_x_continuous(breaks = seq(1960, 2020, 5)) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(
    title = "Music genres of the Billboard Hot 100",
    subtitle = "Proportion of all song genres by year according to Spotify",
    caption = "Source: Data.World, Billboard.com and Spotify · Graphic: Georgios Karamanis"
  ) +
  theme_void()
```



